create table customer (id int not null auto_increment,
                       name varchar(255),
                       registration_number varchar(255),
                       cif varchar(255),
                       account varchar(255),
                       bank varchar(255),
                       headquarters varchar(255),
                       primary key(id));
create table provider (id int not null auto_increment,
                       name varchar(255),
                       registration_number varchar(255),
                       cif varchar(255),
                       account varchar(255),
                       bank varchar(255),
                       headquarters varchar(255),
                       series varchar(255) not null,
                       phone_number varchar(12),
                       cssvn int,
                       vat_percent int,
                       primary key(id));
create table expedition_data(id int not null auto_increment,
                             delegate_name varchar(255),
                             personal_id_info varchar(255),
                             vehicle_number varchar(255),
                             expedition_date date,
                             primary key(id));
create table provider_service(id int not null auto_increment,
                              service_name varchar(255),
                              primary key(id));
create table invoice(id int not null auto_increment,
                    create_date date, monetary_unit varchar(10),
                    net_amount double, amount double,
                    vat_value double, provider_service_id int,
                    expedition_data_id int,
                    primary key(id),
                    constraint fk_provider_service foreign key(provider_service_id) REFERENCES provider_service(id),
                    constraint fk_expedition_data foreign key(expedition_data_id) REFERENCES expedition_data(id));
create table provider_invoice(id int not null auto_increment,
                              provider_id int,
                              invoice_id int,
                              constraint fk_provider_pi foreign key(provider_id) references provider(id),
                              constraint fk_invoice_pi foreign key(invoice_id) references invoice(id),
                              primary key(id));
create table provider_customer(id int not null auto_increment,
                               provider_id int,
                               customer_id int,
                               primary key(id),
                               constraint fk_provider_pc foreign key(provider_id) references provider(id),
                               constraint fk_customer foreign key(customer_id) references customer(id));
create table receipt(id int not null auto_increment,
                       receipt_number int,
                       invoice_id int,
                       primary key(id),
                       constraint ux_invoice_id unique(invoice_id),
                       constraint fk_invoice_r foreign key(invoice_id) references invoice(id));